import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localfont from "next/font/local";
import "./globals.css";

//const inter = Inter({ subsets: ["latin"] });

const dungeon = localfont(
  {
    src: [
      {
        path: "../public/fonts/DungeonFont.ttf",
        weight: "100"
      }
    ],
    variable: "--font-dungeon"
  }
);

const enchanted = localfont(
  {
    src: [
      {
        path: "../public/fonts/Enchanted_Land.otf",
        weight: "100"
      }
    ],
    variable: "--font-enchanted"
  }
);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full w-full">
      <body className={`h-full w-full mt-0 ${dungeon.variable} ${enchanted.variable}`}>{children}</body>
    </html>
  );
}
